name: Daily Post Creator

on:
  schedule:
    - cron: '30 2 * * *'  # 8:00 AM IST
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create post file
        run: |
          mkdir -p posts

          DATE=$(date -u +"%Y-%m-%d" -d "330 minutes")
          NUM_EXISTING=$(ls posts | wc -l | tr -d ' ')
          TOPIC_TYPE=$(( NUM_EXISTING % 2 == 0 ? 0 : 1 ))

          if [ "$TOPIC_TYPE" -eq 0 ]; then
            TOPIC="js"
            TOPIC_NAME="JavaScript"
          else
            TOPIC="ts"
            TOPIC_NAME="TypeScript"
          fi

          FILENAME="posts/${DATE}-${TOPIC}-daily-post.md"

          echo "Creating post file: $FILENAME"

          echo -e "# 📌 Daily ${TOPIC_NAME} Post – ${DATE}\n" > "$FILENAME"
          echo -e "## 🔥 Hook\n_A quick summary that grabs attention._\n" >> "$FILENAME"
          echo -e "## 💡 Insight\n_Explain the concept clearly, simply._\n" >> "$FILENAME"
          echo -e "## 🧪 Code Example\n\`\`\`${TOPIC}\n// Your example here\n\`\`\`\n" >> "$FILENAME"
          echo -e "## 🚀 Takeaway\n_Summarize why it matters and when to use it._\n" >> "$FILENAME"
          echo -e "## 🧠 Engage\n💬 Ask a question to prompt discussion or reflection.\n" >> "$FILENAME"
          echo -e "\n---\n\n#${TOPIC_NAME// /} #WebDevelopment #Frontend #CodingTips" >> "$FILENAME"

          git config user.name "Daily Post Bot"
          git config user.email "bot@daily-post.com"
          git add "$FILENAME"
          git commit -m "chore: generate ${TOPIC_NAME} post template for ${DATE}" || echo "Nothing to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}